name: Actions Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Behave and Playwright
      run: |
        pip install behave playwright

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.14.0/allure-2.14.0.zip
        unzip allure-2.14.0.zip
        sudo mv allure-2.14.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Make files in features directory executable
      run: find ./features -type f -exec chmod +x {} +

    - name: Generate Allure report
      run: allure generate --clean -o allure-report

    - name: Push to gh-pages branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
