name: Actions Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependancies
      run: pip install -r requirements.txt
           # sudo apt-add-repository "deb https://d1.bintray.com/qameta/generic/ all main"
           # sudo apt-get update
           # sudo apt-get install allure

    - name: Run Playwright tests
      run: 
        git update-index --chmod=+x ./features/amazon.feature

    
    - name: Genreate Allure report
      run: 
        allure generate --clean -o allure-report

    
    - name: Deploy to Github Pages
      uses: 
        peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
