name: Actions Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Behave and Playwright
      run: |
        pip install behave playwright

    - name: Install Allure
      run: |
        sudo apt-add-repository "deb https://dl.bintray.com/qameta/generic/ all main"
        sudo apt-get update
        sudo apt-get install allure

    - name: Make files in features directory executable
      run: find ./features -type f -exec chmod +x {} +

    - name: Generate Allure report
      run: allure generate --clean -o allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
