name: Actions Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Behave and Playwright
      run: |
        pip install behave
        pip install playwright

    - name: Make files in features directory executable
      run: 
        find ./features -type f -exec chmod +x {} +

    - name: Run Allure Docker container to generate the report
      run: |
        docker run -v ${PWD}:/allure-results \
                   -v ${PWD}/allure-report:/allure-report \
                   -e "ALLURE_RESULTS=/allure-results" \
                   -e "ALLURE_REPORT=/allure-report" \
                   allureframework/allure-docker:latest generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
